server:
  port: 9007
spring:
  application:
    name: exchange-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      import: "optional:configserver:"
