server:
  port: 9002
spring:
  application:
    name: account-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
