create schema if not exists bank;

create table if not exists bank.user_account
(
    id              integer generated by default as identity primary key,
    username        varchar not null,
    currency        varchar not null,
    "exists"        boolean,
    "value"         double,
    constraint uk_user_role unique (username, currency)
);