spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bank
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: frontend
            client-secret: Udyd28MFJcB8XuBpAmI1fVI7PilNtNjH
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - openid
              - view_all
              - microprofile-jwt

  cloud:
    openfeign:
      oauth2:
        enabled: true

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false

keycloak:
  auth-server-url: http://localhost:8082
  realm: bank
  admin:
    realm: master
    client-id: admin-cli
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, busshutdown

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    feign.client: DEBUG