spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bank
            authorization-uri: http://localhost:8082/realms/bank/protocol/openid-connect/auth
            token-uri: http://localhost:8082/realms/bank/protocol/openid-connect/token
            user-info-uri: http://localhost:8082/realms/bank/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8082/realms/bank/protocol/openid-connect/certs
        registration:
          frontend:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: frontend
            client-secret: Udyd28MFJcB8XuBpAmI1fVI7PilNtNjH
            scope:
              - profile
              - openid
              - view_all
              - microprofile-jwt
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

keycloak:
  auth-server-url: http://localhost:8082
  realm: bank
  admin:
    realm: master
    client-id: admin-cli
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, busshutdown