spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - TokenRelay
            - RewritePath=/account-service/(?<segment>.*), /${segment}
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/frontend/**
          filters:
            - TokenRelay
            - RewritePath=/frontend/(?<segment>.*), /${segment}
        - id: blocker-service
          uri: lb://blocker-service
          predicates:
            - Path=/blocker-service/**
          filters:
            - TokenRelay
            - RewritePath=/blocker-service/(?<segment>.*), /${segment}
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - TokenRelay
            - RewritePath=/notification-service/(?<segment>.*), /${segment}
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer-service/**
          filters:
            - TokenRelay
            - RewritePath=/transfer-service/(?<segment>.*), /${segment}
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange-service/**
          filters:
            - TokenRelay
            - RewritePath=/exchange-service/(?<segment>.*), /${segment}
        - id: exchange-generator
          uri: lb://exchange-generator
          predicates:
            - Path=/exchange-generator/**
          filters:
            - TokenRelay
            - RewritePath=/exchange-generator/(?<segment>.*), /${segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/bank

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, busshutdown
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG